package main

import "strings"

func previewDocument() string {
	document := strings.Replace(previewHTML, "</head>", "<style>"+generatedPageCSS+"</style></head>", 1)
	document = strings.Replace(document, "function render(s){", generatedPageJS+"\nfunction render(s){if(s.blueprint&&s.blueprint.root&&s.blueprint.root.primitive){renderGenerated(s);return}", 1)
	return document
}

const generatedPageCSS = `
.design-page{--line:rgba(255,255,255,.1);--quiet:#8c8b94;min-height:100vh;background:#08080a;overflow:clip}.design-page [data-primitive]{min-width:0}.p-frame{position:relative;max-width:1280px;margin:auto;border-top:1px solid var(--line);isolation:isolate}.p-frame.inset-compact{padding:72px 52px}.p-frame.inset-balanced{padding:112px 52px}.p-frame.inset-expansive{padding:156px 52px}.p-frame.height-screen{min-height:calc(100vh - 74px);display:grid;align-items:center}.p-frame.height-tall{min-height:720px;display:grid;align-items:center}.p-frame.surface-atmosphere:before,.p-frame.surface-accent-wash:before{content:"";position:absolute;z-index:-1;inset:8% -12%;background:radial-gradient(circle at 68% 35%,var(--glow),transparent 48%);pointer-events:none}.p-frame.surface-accent-wash{margin-block:70px;border:1px solid var(--line);border-radius:30px;overflow:hidden}.p-frame.surface-contrast{max-width:none;background:rgba(255,255,255,.025)}
.p-grid{display:grid;grid-template-columns:repeat(var(--cols,2),minmax(0,1fr));gap:var(--gap,28px);align-items:var(--align,stretch)}.p-grid.reverse{direction:rtl}.p-grid.reverse>*{direction:ltr}.p-stack,.p-cluster{display:flex;flex-direction:column;gap:var(--gap,18px);align-items:var(--align,stretch)}.p-cluster.axis-horizontal{flex-direction:row;flex-wrap:wrap}.p-cluster.align-between{justify-content:space-between;align-items:center}.p-overlay{position:relative;min-height:620px;display:grid;align-items:center}.p-overlay>*{grid-area:1/1}.p-overlay>.p-artifact{z-index:-1;opacity:.82}.p-overlay>.p-cluster{position:relative;z-index:1;max-width:760px;padding:clamp(24px,6vw,76px)}.p-overlay.align-center>.p-cluster{justify-self:center;text-align:center}.p-overlay.align-end>.p-cluster{justify-self:end;text-align:right}.p-rail{display:grid;grid-auto-flow:column;grid-auto-columns:minmax(310px,1fr);gap:var(--gap,22px);overflow-x:auto;scroll-snap-type:x mandatory;padding-bottom:18px}.p-rail>*{scroll-snap-align:start}.span-5{grid-column:span 5}.span-7{grid-column:span 7}
.role-navigation{height:74px;max-width:1280px;margin:auto;padding:0 44px;border-bottom:1px solid var(--line);position:relative;z-index:5}.role-navigation .role-mark{font-size:15px;font-weight:780;color:#f4f3f6}.role-navigation .role-mark:before{content:"ϟ";display:inline-grid;place-items:center;width:29px;height:29px;margin-right:10px;border-radius:8px;background:var(--accent);color:#09090b}.role-navigation .role-label{font:9px ui-monospace,monospace;letter-spacing:.15em;color:#66656e}.p-text{max-width:760px}.role-eyebrow{font:10px ui-monospace,monospace;letter-spacing:.18em;text-transform:uppercase;color:var(--accent)}.role-claim{margin:0;white-space:pre-line;text-wrap:balance;letter-spacing:-.065em;line-height:.94;font-weight:640}.scale-monumental{font-size:clamp(70px,10vw,150px);max-width:1100px}.scale-display{font-size:clamp(58px,7.5vw,112px)}.scale-large{font-size:clamp(44px,5.4vw,78px)}.role-explanation{max-width:590px;color:var(--quiet);font-size:16px;line-height:1.75}.emphasis-expressive{font-style:italic}.align-center>.role-explanation{margin-inline:auto}.align-end>.role-explanation{margin-left:auto}.p-action{justify-self:start;width:max-content;border:0;border-radius:8px;padding:14px 19px;background:var(--accent);color:#09090b;font:750 12px ui-sans-serif,sans-serif;cursor:pointer}.role-secondary{background:#f2f1f4}.scale-large.p-action{padding:18px 25px;font-size:13px}
.p-collection{display:grid;grid-template-columns:repeat(var(--cols,3),minmax(0,1fr));gap:var(--gap,13px)}.design-item{min-height:175px;padding:26px;border:1px solid var(--line);background:rgba(255,255,255,.025);overflow:hidden}.shape-soft .design-item{border-radius:16px}.design-item small{display:block;color:var(--accent);font:9px ui-monospace,monospace;letter-spacing:.12em;text-transform:uppercase}.design-item strong{display:block;margin:18px 0 9px;font-size:24px;letter-spacing:-.04em}.design-item p{margin:0;color:#777680;font-size:12px;line-height:1.65}.design-item em{display:block;margin-top:18px;color:#f4f2f7;font:normal 44px/1 ui-sans-serif,sans-serif;letter-spacing:-.07em}.role-metrics .design-item{min-height:135px}
.p-artifact{position:relative;min-height:440px;border:1px solid var(--line);background:#0c0c10;overflow:hidden;box-shadow:0 30px 110px rgba(0,0,0,.36),0 0 100px var(--glow)}.p-artifact.shape-soft{border-radius:22px}.p-artifact.shape-round{border-radius:50%;aspect-ratio:1;min-height:0}.artifact-grid{position:absolute;inset:0;background-image:linear-gradient(rgba(255,255,255,.045) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.045) 1px,transparent 1px);background-size:42px 42px;mask-image:radial-gradient(circle,#000,transparent 82%)}.artifact-core{position:absolute;left:50%;top:50%;width:32%;aspect-ratio:1;transform:translate(-50%,-50%);border:1px solid var(--accent);border-radius:50%;background:radial-gradient(circle,var(--accent),var(--soft) 22%,transparent 67%);box-shadow:0 0 85px var(--glow)}.artifact-core:before,.artifact-core:after{content:"";position:absolute;inset:-38%;border:1px solid var(--accent);border-radius:47% 53% 42% 58%;opacity:.3}.artifact-core:after{inset:-78%;transform:rotate(47deg)}.artifact-wave{position:absolute;left:7%;right:7%;top:50%;height:2px;background:var(--accent);transform:skewY(-7deg);box-shadow:0 -54px 0 rgba(255,255,255,.07),0 54px 0 rgba(255,255,255,.07)}.artifact-wave:after{content:"";position:absolute;inset:-90px 0;background:linear-gradient(180deg,var(--soft),transparent);clip-path:polygon(0 68%,8% 43%,17% 72%,26% 24%,36% 61%,44% 18%,55% 59%,65% 30%,75% 74%,84% 22%,93% 48%,100% 10%,100% 100%,0 100%)}.artifact-specimens{position:absolute;inset:11%;display:grid;grid-template-columns:repeat(3,1fr);gap:15px}.artifact-specimens i{border:1px solid var(--line);border-radius:50%;background:radial-gradient(circle at 35% 30%,var(--accent),var(--soft) 20%,transparent 60%)}.artifact-specimens i:nth-child(2){transform:translateY(50px)}.artifact-type{position:absolute;inset:0;display:grid;place-items:center;color:var(--accent);font-size:clamp(90px,15vw,230px);font-weight:800;letter-spacing:-.1em;opacity:.62}.artifact-runtime{position:absolute;inset:0;padding:44px;color:#787781;font:13px/2.2 ui-monospace,monospace}.artifact-runtime b{color:var(--accent);font-weight:500}.artifact-tag{position:absolute;color:var(--accent);font:9px ui-monospace,monospace;letter-spacing:.13em}.artifact-tag.a{left:8%;top:9%}.artifact-tag.b{right:8%;bottom:9%;color:#6d6c75}.motion-drift .artifact-core{animation:astfloat 5s ease-in-out infinite}.motion-orbit .artifact-core:before{animation:orbit 12s linear infinite}.motion-pulse .artifact-core{animation:breathe 3.5s ease-in-out infinite}.p-rule{height:1px;background:var(--line)}
@media(max-width:820px){.role-navigation{padding:0 22px}.role-navigation .role-label{display:none}.p-frame.inset-compact,.p-frame.inset-balanced,.p-frame.inset-expansive{padding:72px 24px}.p-frame.height-screen,.p-frame.height-tall{min-height:0;display:block}.p-frame.surface-accent-wash{margin:30px 16px}.p-grid{grid-template-columns:1fr!important}.p-grid>*{grid-column:auto!important}.p-grid.reverse{direction:ltr}.p-overlay{min-height:560px}.p-overlay>.p-cluster{align-self:end;padding:28px 20px;background:linear-gradient(transparent,rgba(8,8,10,.92) 22%)}.p-rail{grid-auto-columns:minmax(82vw,1fr)}.p-collection{grid-template-columns:1fr}.scale-monumental{font-size:clamp(54px,17vw,82px)}.scale-display{font-size:clamp(48px,14vw,70px)}.scale-large{font-size:clamp(40px,11vw,58px)}.p-artifact{min-height:340px}.role-navigation .p-action{padding:10px 12px}}
@media(prefers-reduced-motion:reduce){.design-page *{animation:none!important;scroll-behavior:auto!important}}
`

const generatedPageJS = `
const safeClass=s=>String(s||'').toLowerCase().replace(/[^a-z0-9-]/g,'');
function nodeClasses(n){const p=safeClass(n.primitive),l=n.layout||{},st=n.style||{},i=n.interaction||{};return ['p-'+p,'role-'+safeClass(n.role),'axis-'+safeClass(l.axis),'align-'+safeClass(l.align),'inset-'+safeClass(l.inset),'height-'+safeClass(l.minHeight),'surface-'+safeClass(st.surface),'shape-'+safeClass(st.shape),'scale-'+safeClass(st.scale),'emphasis-'+safeClass(st.emphasis),'motion-'+safeClass(i.motion),'span-'+Number(l.span||0),l.reverse?'reverse':''].join(' ')}
function layoutStyle(n){const l=n.layout||{},gap={small:'12px',medium:'22px',large:'48px'}[l.gap]||'22px';return '--cols:'+Math.max(1,Math.min(12,Number(l.columns||2)))+';--gap:'+gap+';--align:'+({start:'flex-start',center:'center',end:'flex-end',stretch:'stretch'}[l.align]||'stretch')}
function renderItems(n){return (n.content?.items||[]).map((item,index)=>'<article class="design-item"><small>'+esc(item.label||('SIGNAL 0'+(index+1)))+'</small>'+(item.value?'<em>'+esc(item.value)+'</em>':'')+(item.title?'<strong>'+esc(item.title)+'</strong>':'')+(item.body?'<p>'+esc(item.body)+'</p>':'')+'</article>').join('')}
function renderArtifact(n,s){const kind=safeClass(n.visual?.kind||'signal-field');let core='<div class="artifact-core"></div>';if(kind==='telemetry'||kind==='depth-map'||kind==='signal-field')core='<div class="artifact-wave"></div>';if(kind==='specimen-field')core='<div class="artifact-specimens"><i></i><i></i><i></i></div>';if(kind==='type-sculpture')core='<div class="artifact-type">'+esc((s.brand||'F').slice(0,2).toUpperCase())+'</div>';if(kind==='runtime')core='<div class="artifact-runtime"><b>observe</b>("'+esc(n.id)+'")<br>compose("'+esc(n.role)+'")<br>verify("live")<br><b>evolve</b>(generation.'+esc(s.generation)+')</div>';return '<div class="'+nodeClasses(n)+'" data-primitive="artifact" data-visual="'+kind+'"><div class="artifact-grid"></div>'+core+'<span class="artifact-tag a">'+esc(kind.toUpperCase())+' / '+esc(s.world)+'</span><span class="artifact-tag b">GEN '+String(s.generation||1).padStart(2,'0')+' · LIVE</span></div>'}
function renderText(n,state){const c=n.content||{},role=n.role||'label',cls=nodeClasses(n);if(role==='eyebrow')return '<p class="'+cls+'" data-primitive="text">'+esc(c.eyebrow||c.body)+'</p>';if(role==='claim'){const tag=state.hasH1?'h2':'h1';state.hasH1=true;return '<'+tag+' class="'+cls+'" data-primitive="text">'+esc(c.headline)+'</'+tag+'>'}if(role==='mark')return '<div class="'+cls+'" data-primitive="text">'+esc(c.headline)+'</div>';return '<p class="'+cls+'" data-primitive="text">'+esc(c.body||c.headline)+'</p>'}
function renderNode(n,s,state){if(!n||!n.primitive)return '';const p=safeClass(n.primitive),cls=nodeClasses(n),style=layoutStyle(n);if(p==='text')return renderText(n,state);if(p==='artifact')return renderArtifact(n,s);if(p==='collection')return '<div class="'+cls+'" style="'+style+'" data-primitive="collection">'+renderItems(n)+'</div>';if(p==='action')return '<button class="'+cls+'" type="button" data-primitive="action">'+esc(n.content?.headline||'Continue')+' →</button>';if(p==='rule')return '<div class="'+cls+'" role="presentation" data-primitive="rule"></div>';const children=(n.children||[]).map(child=>renderNode(child,s,state)).join('');if(p==='frame')return '<section class="'+cls+'" data-primitive="frame" data-role="'+safeClass(n.role)+'">'+children+'</section>';if(p==='cluster'&&n.role==='navigation')return '<nav class="'+cls+'" style="'+style+'" aria-label="Primary" data-primitive="cluster">'+children+'</nav>';return '<div class="'+cls+'" style="'+style+'" data-primitive="'+p+'">'+children+'</div>'}
function renderGenerated(s){const p=palettes[s.theme]||palettes.violet,brand=esc(s.brand||'Velocity');document.documentElement.style.setProperty('--accent',p[0]);document.documentElement.style.setProperty('--soft',p[1]);document.documentElement.style.setProperty('--glow',p[2]);const state={hasH1:false};root.innerHTML='<div class="design-page" data-source="GENERATED DESIGN AST">'+renderNode(s.blueprint.root,s,state)+'</div>';offline.classList.add('hidden');document.title=brand+' — '+s.name+' / Generated'}
`
