import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {spawn} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');const temp=await fs.mkdtemp(path.join(await fs.realpath(os.tmpdir()),'jev-tailwind-e2e-'));const evidence=path.join(root,'work/tailwind-e2e');await fs.mkdir(evidence,{recursive:true});let backend,browser,context,logs='';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));async function until(fn,name,time=20000){let last;const deadline=Date.now()+time;while(Date.now()<deadline){try{const value=await fn();if(value)return value}catch(e){last=e}await sleep(90)}throw Error(name+' '+(last||''))}
try{
 await fs.cp(path.join(root,'tailwind-demo/src'),path.join(temp,'src'),{recursive:true});for(const name of ['package.json','tsconfig.json','index.html'])await fs.copyFile(path.join(root,'tailwind-demo',name),path.join(temp,name));await fs.symlink(path.join(root,'tailwind-demo/node_modules'),path.join(temp,'node_modules'));
 await fs.writeFile(path.join(temp,'vite.config.mjs'),`import {defineConfig} from 'vite';import react from '@vitejs/plugin-react';import tw from '@tailwindcss/vite';import jev from ${JSON.stringify(path.join(root,'integration/jev-vite.mjs'))};export default defineConfig({plugins:[react(),tw(),jev()]});`);
 const file=path.join(temp,'src/main.tsx');const original=await fs.readFile(file,'utf8');const source=()=>fs.readFile(file,'utf8');
 backend=spawn(path.join(root,'work/jev-editor'),['-headless','-project',temp],{cwd:root,env:{...process.env,JEV_OFFLINE:'1',TYPESAFE_API_KEY:'JEV_SENTINEL_SOURCE_99172'},stdio:['ignore','pipe','pipe']});backend.stdout.on('data',d=>logs+=d);backend.stderr.on('data',d=>logs+=d);
 const consoleURL=await until(()=>logs.match(/Console: (http:\/\/[^\s]+)/)?.[1],'start');const previewURL=logs.match(/Preview: (http:\/\/[^\s]+)/)[1];
 browser=await chromium.launch({channel:'chrome',headless:true});context=await browser.newContext({viewport:{width:1280,height:900}});const errors=[];context.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));
 const panel=await context.newPage();await panel.goto(consoleURL);const page=await context.newPage();await page.goto(previewURL);
 const state=()=>panel.evaluate(()=>fetch('/__jev/api/state').then(r=>r.json()));
 async function select(id){await until(async()=>await page.getByRole('button',{name:'切换 Jev 元素选择模式'}).getAttribute('aria-pressed')==='true','select mode');await page.locator(`[data-jev-id="${id}"]`).click({position:{x:10,y:10}});await until(async()=>await panel.locator('.selection code').first().innerText()===id,'select '+id)}
 async function prepare(text){const before=await source();await panel.getByLabel('自然语言修改').fill(text);await panel.getByRole('button',{name:'生成 Diff',exact:true}).click();const s=await until(async()=>{const s=await state();if(s.error)throw Error(s.error);const alert=await panel.getByRole('alert').allTextContents();if(alert.length)throw Error(alert.join());return s.pending&&!s.busy?s:false},'prepare '+text);assert.equal(await source(),before,'prepare writes nothing');assert.ok(s.diff.includes('src/main.tsx'));return s;}
 async function accept(){await panel.getByRole('button',{name:'Accept ✓',exact:true}).click();return until(async()=>{const s=await state();if(s.error)throw Error(s.error);return !s.pending&&!s.busy&&s.stages.at(-1)?.name==='Vite refreshed'?s:false},'accept',45000)}
 async function undo(){await panel.getByRole('button',{name:'↶ Undo',exact:true}).click();await until(async()=>{const s=await state();if(s.error)throw Error(s.error);return !s.busy&&!s.canUndo},'undo',45000);assert.equal(await source(),original,'undo byte-exact full source');}
 const button=page.locator('[data-jev-id="purchase-button"]');const bg=()=>button.evaluate(e=>getComputedStyle(e).backgroundColor);await select('purchase-button');await page.mouse.move(0,0);const blue=await bg();const a=await prepare('把这个按钮换成红色');assert.ok(a.diff.includes('bg-red-600'));await accept();let after=await source();assert.notEqual(after,original);assert.equal(await button.getAttribute('class'),'rounded-lg px-4 py-2 text-white hover:bg-blue-700 md:px-6 focus:ring-2 bg-red-600');await page.mouse.move(0,0);await until(async()=>await bg()!==blue,'red computed style');const red=await bg();await page.reload();await until(async()=>await bg()===red,'accepted source persists after reload');assert.equal(await source(),after);await undo();assert.equal(await bg(),blue);
 // Rejection never writes; a new manual revision after a draft cannot be overwritten.
 await select('purchase-button');await prepare('背景换成红色');await panel.getByRole('button',{name:'Reject',exact:true}).click();await until(async()=>!(await state()).pending,'reject');assert.equal(await source(),original);
 await prepare('背景换成红色');await fs.appendFile(file,'\n// manual edit during preview\n');await panel.getByRole('button',{name:'Accept ✓',exact:true}).click();await until(async()=>(await state()).error.includes('revision'),'revision conflict');assert.ok((await source()).endsWith('// manual edit during preview\n'));await panel.getByRole('button',{name:'Reject',exact:true}).click();await fs.writeFile(file,original);await until(async()=>await page.evaluate(()=>globalThis.__JEV_REVISIONS__?.['src/main.tsx'])===createHash('sha256').update(original).digest('hex'),'source reload');
 for(const [text,label] of [['在这个框中间加一个按钮','按钮'],['在框中间加一个‘立即开始’按钮','立即开始']]){
  await select('empty-container');const draft=await prepare(text);assert.equal(draft.intents[0].operation,'insert_child');assert.ok(draft.diff.includes('place-items-center'));await accept();const container=page.locator('[data-jev-id="empty-container"]');const inserted=container.getByRole('button',{name:label,exact:true});assert.equal(await inserted.count(),1);const bounds=await container.boundingBox(),bb=await inserted.boundingBox();assert.ok(Math.abs((bounds.x+bounds.width/2)-(bb.x+bb.width/2))<2);assert.ok(Math.abs((bounds.y+bounds.height/2)-(bb.y+bb.height/2))<2);after=await source();assert.ok(after.includes('Button as JevButton'));assert.equal((after.match(/import.*Button as JevButton/g)||[]).length,1);await page.screenshot({path:path.join(evidence,'insert-desktop.png'),fullPage:true});await panel.screenshot({path:path.join(evidence,'editor-desktop.png'),fullPage:true});await undo();assert.equal(await container.locator('button').count(),0);
 }
 for(const [id,text,expected] of [['occupied-container','在框中间加一个按钮','歧义'],['dynamic-button','背景换成红色','动态 className']]){await select(id);await panel.getByLabel('自然语言修改').fill(text);await panel.getByRole('button',{name:'生成 Diff',exact:true}).click();await until(async()=>(await state()).error.includes(expected),'safe rejection '+id);assert.equal(await source(),original);}
 // Supported expression forms run through the actual source transaction too.
 for(const id of ['template-button','clsx-button','conditional-button']){await select(id);await prepare('背景换成红色');await accept();assert.ok((await page.locator(`[data-jev-id="${id}"]`).getAttribute('class')).includes('bg-red-600'));await undo();}
 for(const width of [390,1280]){await page.setViewportSize({width,height:900});await panel.setViewportSize({width,height:900});for(const p of [page,panel])assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);if(width===390){await page.screenshot({path:path.join(evidence,'demo-mobile.png'),fullPage:true});await panel.screenshot({path:path.join(evidence,'editor-mobile.png'),fullPage:true});}}
 await page.reload();assert.equal(await source(),original);assert.equal(await page.locator('[data-jev-id="empty-container"] button').count(),0);assert.equal(logs.includes('JEV_SENTINEL_SOURCE_99172'),false);assert.deepEqual(errors,[]);
 const report={result:'PASS',scenarios:['A button red + variant preservation + undo','B registered Button centered + undo','C exact quoted label','D occupied-container safe refusal','E dynamic class safe refusal','literal/template/clsx/condition','Reject no writes','revision conflict protects manual edit','390/1280 no overflow','TypeScript + Vite build on accept','reload persistence'],evidence};await fs.writeFile(path.join(evidence,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}catch(e){if(context)for(const [i,p]of context.pages().entries()){await p.screenshot({path:path.join(evidence,'failure-'+i+'.png'),fullPage:true}).catch(()=>{});if(i===0)console.error(await p.locator('body').innerText())}throw e;}finally{if(browser)await browser.close();if(backend)backend.kill('SIGTERM');await sleep(500);await fs.rm(temp,{recursive:true,force:true});}
