import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {inspectProject,createSourcePatch} from './source-core.mjs';
function fixture(source,component=false){const root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'jev-ast-test-')));fs.mkdirSync(path.join(root,'src'));fs.writeFileSync(path.join(root,'package.json'),JSON.stringify({dependencies:{tailwindcss:'4',react:'19'}}));fs.writeFileSync(path.join(root,'src/view.tsx'),source);fs.writeFileSync(path.join(root,'src/style.css'),'@theme { --color-primary:#155e75;--color-primary-foreground:white;--color-brand:#0e7490; }');if(component){fs.mkdirSync(path.join(root,'src/components'),{recursive:true});fs.writeFileSync(path.join(root,'src/components/button.tsx'),'export function Button(props:any){return <button {...props}/>}')}return {root,cleanup:()=>fs.rmSync(root,{recursive:true,force:true})}}
function color(scope={}){return {scope:'selected',family:'appearance',operation:'set_color',direction:'set',magnitude:'subtle',breakpoint:'all',preserve:['content','behavior','responsive'],confidence:1,arguments:{channel:'background',color:{kind:'literal',value:'red',shade:'600'}},...scope}}
function patch(f,intent=color()){const m=inspectProject(f.root);return createSourcePatch({root:f.root,targets:[m.targets.find(t=>t.id==='chosen')],intents:[intent]})}
for(const form of ['"bg-blue-600 px-4 py-2 text-white rounded-lg hover:bg-blue-700 md:bg-green-600 dark:bg-slate-900"','{`bg-blue-600 px-4`}','{clsx("px-4 text-white", enabled && "bg-blue-600")}','{enabled && "bg-blue-600 px-4"}']){
 test('AST class '+form,()=>{const original=`import clsx from 'clsx'; const enabled=true;export const view=<div><button data-jev-id="chosen" className=${form}>购买</button><p className="bg-blue-600">Untouched</p></div>;`;const f=fixture(original);try{const result=patch(f),after=result.files[0].after;assert.equal(fs.readFileSync(path.join(f.root,'src/view.tsx'),'utf8'),original,'prepare must not write');assert.match(after,/bg-red-600/);assert.match(after,/<p className="bg-blue-600">Untouched<\/p>/);assert.match(after,/px-4/);if(form.includes('hover:'))for(const token of ['hover:bg-blue-700','md:bg-green-600','dark:bg-slate-900','py-2','text-white','rounded-lg'])assert.ok(after.includes(token));assert.equal(result.files[0].before,original);fs.writeFileSync(path.join(f.root,'src/view.tsx'),after);assert.equal(inspectProject(f.root).targets[0].id,'chosen');}finally{f.cleanup()}})
}
test('responsive/state channels are independent',()=>{const f=fixture('export const view=<button data-jev-id="chosen" className="bg-blue-600 hover:bg-blue-700 md:bg-green-600 dark:bg-slate-900"/>;');try{const after=patch(f,color({state:'hover'})).files[0].after;assert.ok(after.includes('bg-blue-600'));assert.ok(after.includes('hover:bg-red-600'));assert.ok(!after.includes('hover:bg-blue-700'));assert.ok(after.includes('md:bg-green-600'));assert.ok(after.includes('dark:bg-slate-900'));}finally{f.cleanup()}});
for(const expr of ['calculateClass(state)','styles[variant]','clsx({active:true})'])test('refuse dynamic '+expr,()=>{const f=fixture(`import clsx from 'clsx';const view=<button data-jev-id="chosen" className={${expr}}/>;`);try{assert.throws(()=>patch(f),/动态|仅支持/)}finally{f.cleanup()}});
for(const registered of [false,true])test('insert registered/native '+registered,()=>{const original='export const view=<section><div data-jev-id="chosen" className="h-64 rounded-xl border"></div><p>unchanged</p></section>;';const f=fixture(original,registered);try{const intent={...color(),family:'structure',operation:'insert_child',arguments:{element:'button',placement:'center',label:'立即开始'}};const result=patch(f,intent);assert.equal(result.files[0].before,original);assert.match(result.files[0].after,/立即开始/);assert.match(result.files[0].after,/place-items-center/);assert.match(result.files[0].after,/<p>unchanged<\/p>/);assert.match(result.files[0].after,registered?/import.*Button as JevButton/:/<button/);fs.writeFileSync(path.join(f.root,'src/view.tsx'),result.files[0].after);assert.ok(inspectProject(f.root).targets[0]);}finally{f.cleanup()}});
test('reject occupied/void/list/stale targets',()=>{for(const element of ['<div data-jev-id="chosen"><h1>Keep</h1></div>','<input data-jev-id="chosen"/>']){const f=fixture('export const view='+element+';');try{assert.throws(()=>patch(f,{...color(),operation:'insert_child',arguments:{element:'button',placement:'center'}}),/歧义|容器/)}finally{f.cleanup()}}const f=fixture('export const view=items.map(i=><button data-jev-id="chosen" className="bg-blue-600"/>);');try{assert.throws(()=>patch(f),/共享实例/)}finally{f.cleanup()}const g=fixture('export const view=<button data-jev-id="chosen" className="bg-blue-600"/>;');try{const m=inspectProject(g.root);fs.appendFileSync(path.join(g.root,'src/view.tsx'),'\n// external');assert.throws(()=>createSourcePatch({root:g.root,targets:m.targets,intents:[color()]}),/过期/)}finally{g.cleanup()}});
test('minimal patch only touches AST-selected attribute',()=>{const original='// keep formatting\nconst x = <button  data-jev-id="chosen" className="bg-blue-600 px-4">Keep</button>;\n';const f=fixture(original);try{assert.equal(patch(f).files[0].after,original.replace('className="bg-blue-600 px-4"','className="px-4 bg-red-600"'))}finally{f.cleanup()}});
test('inline styles and responsive insertion ambiguity refused',()=>{const f=fixture('const x=<button data-jev-id="chosen" style={{background:"blue"}} className="bg-blue-600"/>;');try{assert.throws(()=>patch(f),/内联 style/)}finally{f.cleanup()}const g=fixture('const x=<div data-jev-id="chosen" className="md:grid-cols-2"/>;');try{assert.throws(()=>patch(g,{...color(),operation:'insert_child',arguments:{element:'button',placement:'center'}}),/响应式或状态布局/)}finally{g.cleanup()}});
test('insertion replaces conflicting base layout without touching neighboring node',()=>{const f=fixture('const x=<main><div data-jev-id="chosen" className="h-64 grid-cols-2 items-start justify-end"/><p>Keep</p></main>;');try{const after=patch(f,{...color(),operation:'insert_child',arguments:{element:'button',placement:'center'}}).files[0].after;assert.ok(!after.includes('grid-cols-2'));assert.ok(!after.includes('items-start'));assert.ok(!after.includes('justify-end'));assert.ok(after.includes('grid-cols-1'));assert.ok(after.includes('<p>Keep</p>'))}finally{f.cleanup()}});
