// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Accept():Promise<main.EditorState>;

export function ApplyEdit(arg1:main.ApplyRequest):Promise<main.EditorState>;

export function ChooseProject():Promise<main.EditorState>;

export function ConnectPreview(arg1:string):Promise<main.EditorState>;

export function GetState():Promise<main.EditorState>;

export function OpenProject(arg1:string):Promise<main.EditorState>;

export function OpenStage():Promise<string>;

export function Reject():Promise<main.EditorState>;

export function SetOffline(arg1:boolean):Promise<main.EditorState>;

export function SetSelecting(arg1:boolean):Promise<main.EditorState>;

export function StartPreview():Promise<main.EditorState>;

export function Undo():Promise<main.EditorState>;
