// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Evolve() {
  return window['go']['main']['App']['Evolve']();
}

export function Generate(arg1) {
  return window['go']['main']['App']['Generate'](arg1);
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function OpenStage() {
  return window['go']['main']['App']['OpenStage']();
}

export function SelectConcept(arg1) {
  return window['go']['main']['App']['SelectConcept'](arg1);
}
