// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Accept() {
  return window['go']['main']['App']['Accept']();
}

export function ApplyEdit(arg1) {
  return window['go']['main']['App']['ApplyEdit'](arg1);
}

export function ChooseProject() {
  return window['go']['main']['App']['ChooseProject']();
}

export function ConnectPreview(arg1) {
  return window['go']['main']['App']['ConnectPreview'](arg1);
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function OpenProject(arg1) {
  return window['go']['main']['App']['OpenProject'](arg1);
}

export function OpenStage() {
  return window['go']['main']['App']['OpenStage']();
}

export function Reject() {
  return window['go']['main']['App']['Reject']();
}

export function SetOffline(arg1) {
  return window['go']['main']['App']['SetOffline'](arg1);
}

export function SetSelecting(arg1) {
  return window['go']['main']['App']['SetSelecting'](arg1);
}

export function StartPreview() {
  return window['go']['main']['App']['StartPreview']();
}

export function Undo() {
  return window['go']['main']['App']['Undo']();
}
