// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Evolve():Promise<main.DesignResult>;

export function Generate(arg1:string):Promise<main.DesignResult>;

export function GetState():Promise<main.AppState>;

export function OpenStage():Promise<string>;

export function SelectConcept(arg1:number):Promise<main.PageSpec>;
